// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_PiUT6mWGhvC4gFg4bgGddMC5bJYWYJ0',
    appId: '1:261294472938:web:81c2e8ea50449bfe9ba193',
    messagingSenderId: '261294472938',
    projectId: 'weather-app-76215',
    authDomain: 'weather-app-76215.firebaseapp.com',
    storageBucket: 'weather-app-76215.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Ut8j31okXcCr3XaXTrXUpoLnw4zJ3i0',
    appId: '1:261294472938:android:7bcc07a294b66c4b9ba193',
    messagingSenderId: '261294472938',
    projectId: 'weather-app-76215',
    storageBucket: 'weather-app-76215.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASCdrvIBkBAR-QFrjlHu3lUsjdIqT0rtI',
    appId: '1:261294472938:ios:e010d50af1599c2f9ba193',
    messagingSenderId: '261294472938',
    projectId: 'weather-app-76215',
    storageBucket: 'weather-app-76215.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASCdrvIBkBAR-QFrjlHu3lUsjdIqT0rtI',
    appId: '1:261294472938:ios:e010d50af1599c2f9ba193',
    messagingSenderId: '261294472938',
    projectId: 'weather-app-76215',
    storageBucket: 'weather-app-76215.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_PiUT6mWGhvC4gFg4bgGddMC5bJYWYJ0',
    appId: '1:261294472938:web:4b262d166f36aaca9ba193',
    messagingSenderId: '261294472938',
    projectId: 'weather-app-76215',
    authDomain: 'weather-app-76215.firebaseapp.com',
    storageBucket: 'weather-app-76215.firebasestorage.app',
  );
}
